warna = input("Masukan warna: ")
benda = input("Masukan benda: ")
orang = input("Masukan nama orang:")
print('\n')
print("Bunga itu berwarna "+warna)
print(benda+" ini berwarna putih")
print("I love "+orang)